name: flutter_rest_client
description: A rest client module for flutter.
version: 0.1.3
homepage: https://gitlab.com/swivt/rest-client
repository: https://gitlab.com/swivt/rest-client
publish_to: pub.dev


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  mime: ^1.0.1
  http_parser: ^4.0.0
  freezed_annotation: ^1.1.0
  # freezed_annotation: ^1.1.0
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  dio_http_cache:
    git:
      url: https://github.com/queendevelopers/dio-http-cache.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  build_runner: ^2.1.8
  curl_logger_dio_interceptor: ^0.0.3
  pretty_dio_logger: ^1.1.1
